const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

const BOOK_SELECTED = 'BOOK_SELECTED';

const ADD_BOOK = 'ADD_BOOK';
const REMOVE_BOOK = 'REMOVE_BOOK';
const MARK_READ_BOOK = 'MARK_READ_BOOK';
const LOAD_READ_BOOK = 'LOAD_READ_BOOK';

export {
    FETCH_BOOKS_REQUEST,
    FETCH_BOOKS_SUCCESS,
    FETCH_BOOKS_FAILURE,
    BOOK_SELECTED,
    ADD_BOOK,
    REMOVE_BOOK,
    MARK_READ_BOOK,
    LOAD_READ_BOOK
}